owner: tuyencaovn
repo: dpunitystatus

sites:
  - name: DP Unity-Web
    url: https://dpunity.com
  - name: Bimnext-Web
    url: https://bimnext.dpunity.com
  - name: Bimnext-API
    url: https://bimnextapi.dpunity.com

status-website:
  cname: status.dpunity.com
  name: DPUnity Status
i18n:
  footer: © DP Unity 2022 | All rights reserved
